var worldMap=[
    '                                                                         B     B     B     B',
    '                                                                       B     B     B     B',
    '                                                                     B     B   X B     B',
    '                                                                   B     B     B     B     B',
    '                                                                 B   X B     B     B     B',
    '                                      SSS                            B     B     B     B',
    '                                          c   CCCCCCCCC       c    B     B     B     B     B',
    '                                 B  BBXXXBBBB            BBBXXB  B     B   X             B  P',
    '                                 BSBB                   BB    BXXX X B   X B     B  B  BB   cB',
    '                                 BSB                          BXXX B   X B     BXXXXXXXXXXXXBB',
    'BBBB                             BSB                          BBBB     B     B BXBXBBBBBBBBXBB',
    'BP     BBB               CCC     BSB                               X B     B XXXXBXXXBBBXBBXBB',
    'BBBBBB B   c B B BXX c   CCC     BSB                               B B BXB X XXBBBBBXBBBXBBXBB',
    '         BBB B B B   BBB     B   BSB                                          X     X   X  X',
    '             BXBXB  BB       B   BSB                                          X         X  X                                                                                                                                  SCCC',
    '             BBBBB           B   BSB                                          X            X                                                                                                                      CCCCC      S     CC',
    '               B             B    SB                                                                                                                                                              c              B      B   S          c',
    '               B             BBBBBBB                                                                                                                                                             SBBBXXBXX     BXXXXXXXBBBBBBXXXXXXXXBBBBXXBBXXBBXXB',
    '               B                                                                                                                                                                                 S           B                                      ',
    '               B                                                                                                                                                                                 S        BB                                        ',
    '               B                                                                                                                                                                                 S',
    '                                                                                                                                                                                                 S',
    '                                                                                                                                                                                                 S',
    '                                                                                                                                                                                                 S',
    '                                                                                                                                                                                                 S',
    '                                                                                                                                                                                                 S',
    '                                                                                                    c                                                                                            S',
    '                                                                                           SSSSSSSSSB                                                                                            S',
    '                                                                                                      B                                                                                          S',
    '                                                                                                        B                                                                                        S',
    '                                                                                                          B                                                                                      S',
    '                                                                                                            B                                                                                    S',
    '                                                                                                              B                                                                                  S',
    '                                                                                                                B   B                                                  BBBBXXXXXXXXXXXXXXXXB     S',
    '                                                                                                                       BBB                                             B  SC               B     S',
    '                                                                                                                XXXBBB                 C  C  CC                        B  SC       C       B     S',
    '                                                                                                                             BBBS S S S  S  S                          B  SC  S S S  CSC   B     S',
    '                                                                                                                             BBB                 c   XXXXXXXX          B  SXXXXXXXXXXSSX         S',
    '                                                                                                                                                 B         CC          B  SXXXXXXXXXXXXX     CCCCS',
    '                                                                                                                                               XBB  S S S cCC X        B   XXXXXXXXXXXXX',
    '                                                                                                                                                    XXXXX BB  C        B SBXXXXXXXXXXXXX SBB',
    '                                                                                                                                                              C  X     B SSC      CC     SXB',
    '                                                                                                                                                              X  C     B  SCCCCCCS   CCCCSXB',
    '                                                                                                                                                                 C  XXXB  SC             SXB',
    '                                                                                                                                                                 X  C     SBXXXXXXXXXXXXXXXB',
    '                                                                                                                                                                    C  c  SB',
    '                                                                                                                                                                    XBBBXXXB',
    
];
